service: serverless-java
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.HelloWorldHandler
    layers:
      - {Ref: CommonLibsLambdaLayer}

layers:
  commonLibs:
    path: layer
