service: serverless-java
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221

package:
  artifact: target/layer-demo-1.0.0.jar

functions:
  hello:
    handler: com.amazonaws.lambda.LambdaFunctionHandler::handleRequest
    layers:
      - {Ref: CommonLibsLambdaLayer}

layers:
  commonLibs:
    path: layer
