service: demo-serverless-nodejs
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    layers:
      - {Ref: CommonLibsLambdaLayer}

layers:
  commonLibs:
    package:
      artifact: ../nodejs.zip
